---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgCefAVtT+Mr1LiMEL7RTEjv+Rt2bhhCsIZn72fC+1ZBSjoq/0R1VznCVbYl7jSKI1w07SO0OTtz6+C53LXmAHe6bfdq5UJIoRMEqiZu557/HVfeSDfyjH9XAdipgeFYlfQfG+tsgToj6aK0fOjCMpDBEJO/Rjf6iP5jajEncm0U/unDGlx/a6X8yrF8D15k6JqYc+MSgMVmdTwhZg+MC0d9AQLPmgxowcnUOnCi7i6HRA2jA1kRJfFOav4blpSwa2tC0ZsW2nyQ6IIbQ9xvU+2iUhDJCA8gVsotCLiXiwfPzz+rv2OqACSt3W9jXYGleGI3WZNLXujBwfuTbV/yBhKnglT6TRZFrMTA0Fh9L4kSyano48WdzBpcd+AA83IJVjQ6z2NjWChOZJnyoL4vh9Gy72o517OeJIHrVomwZ0RJeMnd9565AsTFOV56innBFiI8yIRx0uge6BdSRETfYssMs8y7qdSHzjbabljQ1cejbeOGRuGnwGsaK3jDc8tcj0L9e9OyvUPsuULbEMOQzyCGDI8SdldphBqfTJGX2a4LMP6mXU3hc2GczhjidEGRnyp7sf2dWcASS9tJ5k1na0kbdA9fjvp/oA9/b2IdTbTh78WJRI4RGZtqrbLu73ojXYrJP+tYmmipaLvkzYnDktGmxF/IDLIzlKhHPHO0zzsjyGVqtXpBkKYiJ2/TYZRH2nFs0/Jtq1f7FbRlCyI1q3wHVDN0MKFPL5wuaCb+7s1iNgEgx44GCNAi/+Jyv1/MWS3jt8uV9rFlnOEQnFQ+pFGMuJaE/liujCW3aXtlxtLS+xe1Nwf3/dOYb6sZ+H+Wsm0wdZU8yEx/PXPK5fR8x9WdQdcPndVK+4kVSSpf0T7VogEKGkp/U0TzrzfFWLWz9KVdZo/T/tn5SInsgnHR5pRizWMEN3GpcV8k0jgwlD4F/Jn76zwtvehm
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
