---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgB4OmxbQTSDqpkZdOAORxO7ap+jE2psPV07SVGMYPCo1LYxNtThdJQyRMOTqrG56xhEULD3qyevf9IggaGIGEDSjVQVK/pAvGR8ex3xd8I5BpUl62E2iGaS4u2Mo7JG69LIbBQ3haC5dTM7qZ2yba3nWlCKeUHCw3haCnc7PNiWtQ2+5Cpa0g1m+sp20Cv53q65S8yZn7zuGF1BCbEgFKFuyvUznXYvNXVm+qlCKjG9Pb5HErhU6Sk1Va7Srf5oM7NdL3sChRQ4o8V3lW3VJcub0rCavxFQAsmsKWGEjXWt8Mr4c7l4lwZv0fZVBl4ZMy0DIXk2jVCH1+UTmrPXb1p54w1/J4W9b9jQdvriIV5v3Vv62baqLQJJp3Yu71xu5LotoHAFqgclskwY4H9bCGPk/IxZXSzFdm4CNv/TCB1tbs8y83CcOjqB/da7ahjL5GrmrLCPX4NHUd78RMBtdvBxIjqq1nQ4NWet8YN9/EXGOOddF5dp4uCWozwm+3cwofCdqR19M5o8FXe9PYPbYPuqFNR7gX1TKypH+v+7QC/t5ORChs4flJ24MNKLggJS8orw8FoHlFnM6W3fCyzMGbHyahsDdOba09KJqde5Ppwrz42cS1URxXjB5lLt0bYOiYwMsXdqZlYAQejzvkhGJf+K7mUiVZOANmmt94tQjhg/EOrnDHPtyOBcXs8uQulDthN6cVinbwocJdbsywNWHlhcNoh3S2ZiQ4btOYJCJRYD0yqRh+JfhNMDatqqDowUcBSJWZN0DQ2TePavbkoIJW5EIs5kyEn+cB/6m2FzuiKiUlcXo7My/9C9jLVMsdedVLuhLILKO2oWh7Rbp3CHKi9YkwQqv/rZKvnJnNHrSI/3qFLquyCP4n9YYMwZQP0KuXAaJSIcIUfWwD3iH5pFcoxl0041kAWalEWJHUFrK3lVBGjUbnZzBhvB
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
