---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgAv4VHvam7KnigJ7OLmPDANM2DggWqSmCkhActOXNvEUEp/ZxxoLa/LPCd5EkHhUsYMDXnjK50UJtpiPusR4tg+I0LvvqR2bsfYf+DHEyOb49pvFk+gpGJa2VgEFOODCJzZS7Ci04c2ZRvfzw6o1tUjFaeZJGVEcEZK+rp7/0YpPYT8d1Mh+Ft9Ebu+QNXUASLaV4QZWBQa/Sxkq9zgje9bJTwdq0CnNfH2ucwJz8TLBcjThDl7fCmfVctdxe+zzWhzQevtnHPeRDZVExRrI8WwN23YlKg8y4lXonMQezCsmQLUnPmlTmGOFA8Xag7gAY8xlUCpgctV94m8jJAU9/0+wa9lfUuqtN3wG/7mDFe9V+Paqnylx7sxJjhrs1O+Stf1vQTO8iMWCLX04oH0jyXabNo+NwEBFcCrCebOjHb7gdX1++tIh3TcYP30FHRzgtMTE13wC6T0YhLdQQ29zEsvJzp3aTFtV49/khbjbGD5K+vNKCOHRAQpn0PXpyUldwQ6kcSoX4/1pI07MmD8XFtRLkjjEUfMA5TqzVQeS6ZuycbDpi4OyO8EoHcpnXXHDRsCm9fSjX0Epn5djsPBSAzm3vDhLmPUmWThSiHK25HqUA9VcwWYi7OGXG7BW2zyCHm2iNbpXG5t/50GaZsUC6IBLHmpCrpCYnKeDGU8QLfAszR/wK7mpcQNy4DvYi7rCrAy5mQir8vyTd+R8gQeEaihPh6rz24DjlkMa01lBvtQu+YNYomvjC1aW2lAPvMQjeo4JRETMcWbcnaID+WnSDtYZQaNdAuFS+obgIKP2vxcf2nW379iMf6ubU9jfBizazp3HesSLvr/5xXPUhsA5Ij9Fbe7hkpOnF5w3zOpc7UE8Ho1BW76sCqXtANm6tzCnN6ZHGD2H7v31ok4uCeGrloX0BKxUIkftZwGjfWWlypuF2kuoreT8B/7
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
