---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-phpmyadmin-secret
  namespace: mariadb-phpmyadmin
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgBHm4bGPUyR8I1TLd1dtlq08xjxszCLGe/gifCs/oo831UpcBU8P3roHP+QFlHfCeIXD4i8gro+QpFe3nJsYUdITMLOrEVe+87A7k54aOwUEzzmbz0+ewoGixiiEdVaFSlOe3f0sNMl5YbT1b0Sffra54FKJQHLgWfOS8I7SxdjZ9kSUlFx6rK6cyGwyYzFsk4w0tp3ID0C3N8IaTx3VAv3UP1+ybr89y/vYGjSFBk/5XbUU+WEpV6H7WSfqZoDFSLY/Iz4b/0d4rt+ytiaIpDG+PrN1kI4oeHetzmps786VDl6sEz/+yaoUb+5mp5/E/NZjORbur1nVSe7czWQcGfkiTh1ZNeq8O2bL5VN0AGh+OHaIp+ku8pE+xZQzxDMRcrJYHgYi82YTJzdYT+TOO0qw1h31i/R6xrXEirponpJIm3tk/xdxmeT2na39FsCKp7eQRFkbV3WM5PyWJFAb3Wu7IP/eghOpvQyrDSeO6e6k+w7+zKhcze46ni1qwJLZkJUMfWf+U0mBp+KOOAux9mcNrOS0blvvXUqTkx855IzAgeZXH4UiFN/mXiYZzVv4zY38+hE1Il56DgRyq/O4P0R3k+iva9/UOoMnTptkrUUpS4lQUnWc2BFA6oIMGT6o8wpTMfgBbMKkm9KxB1ZiIQwgZXLoBMidiU1HQRNygVweblgAnOC+y1bhzD/VzNUdaKrNIMx5zNW4Ri1
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-phpmyadmin-secret
      namespace: mariadb-phpmyadmin
    type: Opaque
