---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-phpmyadmin-secret
  namespace: mariadb-phpmyadmin
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgBE/ZauZATqkuu/lIvI6NNUNDskjdOOn1DJBlPEEdhqVuk/JRxfR398uxXpGscqkJMy9zfdLqzpFfxf382Kg4vLas10ce4MuzUDmZcllNEBPR6utvwJBt92qaBVdy3xE8GkVB6GOaTF2nfP9uRcVMFtEic09hRzKjsZOKil91+cm4JgNoC+CZ0D39Gtr5BqPeZ1FZN96P7TLmvIU//Wb0bxly7AScIRyLD6rKL+dSWeMUl0sla4IZ1J771Ll106g4TZ6HuKJOPV4FP+f88Gw4zRAw5ZnCFIMw5rUZLHil9R9lHV6w1/Y0G6Z5amWynz9eFpBoL7ykf+iwrBAifzXtMms53RgxWE4ojdX3TssjsWq3BcXlmBbG0gIvqWmjSh/+qkUvYXStMHH22ubj1p7H6cw3M06eZjvCo5KfJY8kykWoOnj/8JrkmJiLwBXJjirqy3raN9d7/lSDTrPHZoHDZhDuV4N46upMqqwd+YXRu7HZgEayW+wPozGS9kjNXK/5autTzyr27iYWrYi2RY7dey/wM8L342lQnLW9jSWc4nRUvQcF+9N+DWQvdie4zhRJOZEt42RJ78wMYDL3GPlHtiRyDg+Yjso2GbH67IXL7kn6fpgU5DZ3MZrubTmngt/48q58Td9es6hfKxfI2MK7NTSX59FSO5KjjNs1Fxf00uF/jMU0RLFXoRCKVXXkRUO1VCKeXq+UL2rCF4
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-phpmyadmin-secret
      namespace: mariadb-phpmyadmin
    type: Opaque
