---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-phpmyadmin-secret
  namespace: mariadb-phpmyadmin
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgBFrl9O9t4xzo+lIWtZcV/bbrGcxXQyxJeElBxQ8xBDGVndVujNsxOWceyej3InkxXIyipciv95Kxyjlil/4pIpLy8MpkfKkM27GvBCdcKFG0NvZrXhG4RPkkUVH5kA2myzi/q3279LOG6KBs5F6zufnP3WgdSueKDI7YbMDbu9e3NH6lnOejV4DDXz0TzTg+/04dokpur315GGoSem7W+InggY9qLymkNo48pI4Y1sm28+MHm8cephOT8f7odQ0B3csV/+6WiKmBabY1TCvzsMJnpGTu3t1SUn6CqVrTOv3PiZyxUs5fWGR8374Od8ruhPvwDlYNQR5Yc/eVOMGzcHRcSd1WyyCBnKirACow6C85/UpTZM3NQ/wdNueUDcm6HBp0W0dMMeRi6fuoDyqjIORONJEWvpdxop7zirjaKndN9fQCSaFSDVoSH73hWqfozs1mcmqqPcVOqOWtWjrRCsAPfTJkopzBj/I8KVxdsvSAt63A7unBInF9bNNt7TXmr3jebi+O3xf4xLAzCO84HX1/pJBYjNmwwsIp7BKrwINkQvzeJn4fGyxU4GbxYljIYWowncCrK+CUHwWprubR6ij70CmJg5CyPKTXNrVkIAut1L8nYCFABMWaTNNem+xd2HzFwvA3WTBl7sy4vrqEd1OrC1k2J20S0x0okB0wUFPT61mV26FNCl2/Sy7ORPap6Ckf9RgtSfhfHI
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-phpmyadmin-secret
      namespace: mariadb-phpmyadmin
    type: Opaque
